apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: tweety
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: swithtweety@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: switht-co.kr-tls
  namespace: switht
spec:
  secretName: switht-co.kr-tls
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: server.switht.co.kr
  dnsNames:
    - server.switht.co.kr
