apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-deployment
  namespace: tweety
spec:
  replicas: 2
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      containers:
        - name: member
          # AWS의 ecr 주소 사용
          image: 533267389389.dkr.ecr.ap-northeast-2.amazonaws.com/tweety-member:latest
          ports:
            - containerPort: 8080
          resources:
            # 최대 할당 가능량
            limits:
              cpu: "1"
              memory: "1000Mi"
            # 최소 할당량
            requests:
              cpu: "0.5"
              memory: "500Mi"
          env:
            - name: JAVA_OPTS
              value: "-Xmx3000m"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: REDIS_HOST
                  name: tweety-secrets
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: DB_HOST
                  name: tweety-secrets
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME
                  name: tweety-secrets
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: tweety-secrets
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: tweety-secrets
            - name: JWT_SECRET_RT
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET_RT
                  name: tweety-secrets
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY
                  name: tweety-secrets
            - name: AWS_SECRET
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET
                  name: tweety-secrets
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CLIENT_ID
                  name: tweety-secrets
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CLIENT_SECRET
                  name: tweety-secrets
            - name: KAKAO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: KAKAO_CLIENT_ID
                  name: tweety-secrets
            - name: KAKAO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: KAKAO_CLIENT_ID
                  name: tweety-secrets
            - name: KAFKA_SERVER
              valueFrom:
                secretKeyRef:
                  key: KAFKA_SERVER
                  name: tweety-secrets
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  key: SMTP_USERNAME
                  name: tweety-secrets
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SMTP_PASSWORD
                  name: tweety-secrets
            - name: MQ_HOST
              valueFrom:
                secretKeyRef:
                  key: MQ_HOST
                  name: tweety-secrets
            - name: MQ_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MQ_USERNAME
                  name: tweety-secrets
            - name: MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MQ_PASSWORD
                  name: tweety-secrets
            - name: TWILIO_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: TWILIO_ACCESS_TOKEN
                  name: tweety-secrets
            - name: TWILIO_SID
              valueFrom:
                secretKeyRef:
                  key: TWILIO_SID
                  name: tweety-secrets
            - name: TWILIO_PHONE_NUMBER
              valueFrom:
                secretKeyRef:
                  key: TWILIO_PHONE_NUMBER
                  name: tweety-secrets
          readinessProbe:
            httpGet:
              path: /member-health
              port: 8080
              # 컨테이너 시작 후 지연시간 설정
            initialDelaySeconds: 10
            # 확인 반복 주기
            periodSeconds: 10
            # 요청 타임아웃 설정 - 1초 이내에 안오면 실패
            timeoutSeconds: 1
            # 성공 인식 횟수 설정 - 몇번 성공해야 성공하는지
            successThreshold: 1
            # 연속 실패 횟수 . 연속적으로 5번 실패하면 건강하지 않은 상태로 판단하여 기존 서버 종료시키지 않음
            failureThreshold: 5
