spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/switht_payment
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    tomcat:
      max-active: 5
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    consumer:
      #      group-id는 컨슈머 그룹을 식별하는 ID. 동일한 그룹 ID를 가진 컨슈머들을 메시지를 분담해서 consume.
      group-id: payment-group
      #      가장 처음으로 사용 가능한 메시지부터 읽기 시작
      auto-offset-reset: earliest
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: AWS_MSK_IAM
      sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;
      sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler


jwt:
  expiration: 300
  secretKey: ${JWT_SECRET}
  expirationRt: 14400
  secretKeyRt: ${JWT_SECRET_RT}

imp:
  code: ${IMP_CODE}
  key: ${IMP_KEY}
  secret: ${IMP_SECRET}

